name = abriglass
title = Abriglass
description = Adds coloured glass, patterned stained glass, glass lights and one way windows.
depends = default, dye
optional_depends = maptools
min_minetest_version = 5.10
